title: Sameer N Jadhav
logo: /img/411562bd-ec6c-47a4-8f64-a0504599d0d1.jpg
description: Data Scientist with broad-based experience in building data-intensive applications. Proficient in data modeling, data processing, and machine learning algorithms, as well as programming languages including Python and R. Capable of improving the legacy systems to translate business and functional qualifications into substantial deliverables. A highly motivated individual with a penchant for gaining in-depth knowledge and excellent communication skills, seeking a data science role.
[Linkedin](www.linkedin.com/in/sameeerjadhav)
show_downloads: False
theme: jekyll-theme-minimal
