title: Sameer N Jadhav
logo: /img/BEBA7DE0-CD45-4D5A-99AC-330E255F3E64_1_105_c.jpeg
description: Data Scientist with 3 years of broad-based experience in building data-intensive applications. Proficient in data modeling, data processing, and machine learning algorithms, as well as programming languages including Python and R. Capable of improving the legacy systems to translate business and functional qualifications into substantial deliverables. A highly motivated individual with a penchant for gaining in-depth knowledge and excellent communication skills, seeking a data science role
show_downloads: False
theme: jekyll-theme-minimal
